### PR TITLE
use vagrant to reproduce the environment for development/testing

### PR DESCRIPTION
**Pull request by joestein**
When trying the readme i got an error

module.js:340
    throw err;
          ^
Error: Cannot find module 'buffermaker'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/lib/KafkaConnector.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

so I reproduced it on the VM, maybe something else has to be done with another include or package or something?

### CODE REVIEW

**Comment by wurstmeister** [comment]
Hi Joe, 

thanks for the feedback. Did you run 'npm install'? 

I will update the readme and have a look at your pull request. 

Thanks again.

**Comment by wurstmeister** [comment]
I've updated the readme and made the broker in the sample producer and consumer configurable. so you should be able to use them against the broker running in vagrant.

**Comment by joestein** [comment]
producing and consuming look good in the vm awesome!

**Comment by wurstmeister** [comment]
Thank you!

**Pull request merged**
